/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e1e3e2',
        'background': '#f8faf9',
        'on-primary': '#ffffff',
        'surface-container-high': '#e6e9e8',
        'surface-container-low': '#f2f4f3',
        'on-primary-container': '#9dd090',
        'surface-tint': '#3b6934',
        'secondary-fixed-dim': '#b1cade',
        'secondary-fixed': '#cce6fb',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'tertiary-container': '#3a5640',
        'surface-bright': '#f8faf9',
        'on-surface': '#191c1c',
        'on-background': '#191c1c',
        'on-primary-fixed': '#002201',
        'primary-container': '#2d5a27',
        'secondary-container': '#cce6fb',
        'surface-container-lowest': '#ffffff',
        'surface': '#f8faf9',
        'tertiary-fixed-dim': '#afceb2',
        'tertiary-fixed': '#caebcd',
        'inverse-surface': '#2e3131',
        'on-tertiary-fixed': '#05210e',
        'on-secondary-fixed': '#021e2d',
        'on-secondary-container': '#4f6779',
        'outline-variant': '#c2c9bb',
        'on-error': '#ffffff',
        'error': '#ba1a1a',
        'outline': '#72796e',
        'on-tertiary-container': '#abcaae',
        'tertiary': '#243f2a',
        'surface-variant': '#e1e3e2',
        'on-tertiary-fixed-variant': '#314d37',
        'error-container': '#ffdad6',
        'surface-container': '#eceeed',
        'on-secondary-fixed-variant': '#31495b',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#42493e',
        'on-primary-fixed-variant': '#23501e',
        'inverse-primary': '#a1d494',
        'secondary': '#496173',
        'inverse-on-surface': '#eff1f0',
        'primary-fixed': '#bcf0ae',
        'surface-dim': '#d8dada',
        'primary': '#154212',
        'primary-fixed-dim': '#a1d494',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
